// Generated by CoffeeScript 1.10.0
(function() {
  var cson, loaderUtils;

  cson = require('cson-parser');

  loaderUtils = require('loader-utils');

  module.exports = function(contents) {
    var jsonString, query;
    if (typeof this.cacheable === "function") {
      this.cacheable();
    }
    query = loaderUtils.parseQuery(this.query);
    jsonString = JSON.stringify(cson.parse(contents));
    if (query.file) {
      return jsonString;
    } else {
      return "module.exports = " + jsonString;
    }
  };

}).call(this);
